name: Build iOS Simulator .app

on:
  workflow_dispatch:

jobs:
  build-ios-simulator:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Show repo root (debug)
        run: |
          echo "=== Repo root listing ==="
          ls -la

      - name: Install workloads (MAUI etc.)
        run: |
          dotnet workload restore

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Try build for iOS Simulator (x64 then arm64)
        shell: bash
        run: |
          set -euo pipefail
          OUTDIR=./output
          rm -rf "$OUTDIR"
          mkdir -p "$OUTDIR"

          echo "=== Attempt build for iossimulator-x64 ==="
          if dotnet build "./A2Z Browser/A2Z Browser.csproj" -c Release -f net9.0-ios -p:Platform="iPhoneSimulator" -p:RuntimeIdentifier=iossimulator-x64 -o "$OUTDIR"; then
            echo "Built for iossimulator-x64"
          else
            echo "x64 build failed — trying iossimulator-arm64"
            if dotnet build "./A2Z Browser/A2Z Browser.csproj" -c Release -f net9.0-ios -p:Platform="iPhoneSimulator" -p:RuntimeIdentifier=iossimulator-arm64 -o "$OUTDIR"; then
              echo "Built for iossimulator-arm64"
            else
              echo "Both simulator builds failed. See the build logs above for errors."
              exit 1
            fi
          fi

      - name: Show output directory contents (debug)
        run: |
          echo "=== output dir ==="
          ls -la ./output || true
          echo "=== recursive listing ==="
          find ./output -maxdepth 4 -type f -print || true

      - name: Zip .app artifact (only if .app exists)
        run: |
          cd output
          shopt -s nullglob
          APPS=(*.app)
          if [ ${#APPS[@]} -eq 0 ]; then
            echo "ERROR: No .app found in ./output — build step must have failed."
            echo "Contents of output (one level up):"
            ls -la .. || true
            exit 1
          fi
          zip -r ../ios-simulator-app.zip *.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: ios-simulator-app.zip
