name: Build iOS Simulator .app

on:
  workflow_dispatch:

jobs:
  build-ios-simulator:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'     # you said your project targets net9.0

      - name: Install required workloads
        # This installs workloads the project needs (maui/android/ios etc).
        run: |
          dotnet workload restore

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Publish iOS simulator app
        run: |
          # IMPORTANT:
          # 1) Use the correct path to your project/solution. Your files show A2Z Browser has a space.
          # 2) Quoting the path avoids problems with spaces.
          #
          # Option A: publish the .sln (works if the solution file is at repo root)
          dotnet publish "./A2Z Browser.sln" -c Release -f net9.0-ios -p:Platform="iPhoneSimulator" -p:RuntimeIdentifier=iossimulator-x64 -o ./output || true

          # Option B (safer if sln is in subfolder): publish the specific project file
          # dotnet publish "./A2Z Browser/A2Z Browser.csproj" -c Release -f net9.0-ios -p:Platform="iPhoneSimulator" -p:RuntimeIdentifier=iossimulator-x64 -o ./output || true

      - name: Show output files for debugging
        run: ls -la ./output || true

      - name: Zip .app artifact
        run: |
          cd output || exit 0
          zip -r ../ios-simulator-app.zip *.app || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: ios-simulator-app.zip
